pub const ERROR_CODE_FAILED_TO_SEND_MESSAGE: i32 = -1;
pub const ERROR_CODE_FAILED_TO_RECV_RESPONSE_FROM_SERVER: i32 = -2;
pub const ERROR_CODE_SERVER_RETURNS_FAIL: i32 = -3;
pub const ERROR_CODE_SERVER_REFUSE_TO_CONNECT: i32 = -4;
pub const ERROR_CODE_WRITER_ERROR: i32 = -5;
